# Generated by Django 4.1.2 on 2022-10-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
                ('ip', models.GenericIPAddressField(verbose_name='IP Address')),
                ('udp', models.IntegerField(verbose_name='UDP Port')),
                ('community', models.CharField(max_length=20, verbose_name='Community')),
            ],
        ),
    ]
