# Generated by Django 4.1.2 on 2022-10-29 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='users',
            field=models.ManyToManyField(related_name='configs', to=settings.AUTH_USER_MODEL),
        ),
    ]
